### ISSUE TITLE
Deleting client data does not work

### ISSUE THREAD

**Issue by nexsja** [idenfy/Documentation#28]
[IdentificationDeletion](https://github.com/idenfy/Documentation/blob/master/pages/IdentificationDeletion.md) describes a way to delete client data, yet calling the `delete` endpoints I receive a `501 Not Implemented`

```
POST https://ivs.idenfy.com/api/v2/delete

HTTP/1.1 501 Not Implemented
Date: Fri, 27 Mar 2020 09:39:02 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Server: nginx
X-Frame-Options: SAMEORIGIN
Vary: Origin

<Response body is empty>
```

Is the documentation misleading or am I doing something incorrectly?

**Comment by laimonassutkus** [comment]
Hello. The functionality is not implemented.
