### ISSUE TITLE
Another repo except Jitpack

### ISSUE THREAD

**Issue by bahacan19** [idenfy/Documentation#94]
Hi
As all we know, Jitpack server is sometime down for over 24 hours. And this makes most of the pipelines of all world crash. As Ozan SuperApp team we have decided to move our dependencies from Jitpack into other possible artifact repositories. Did you ever deployed into other alternatives? Or are you planning to? 

Jitpack is down catastrophe is discussed in here:
https://github.com/jitpack/jitpack.io/issues/5239#issuecomment-1363291470  

Regards

**Comment by viktasidenfy** [comment]
We're still considering it. If we get more requests, we might move to another repository. But now, we will stay with jitpack, since the migration process is not that simple.
