### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by epodkorytov** [idenfy/Documentation#96]
dyld: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: .../Frameworks/IdenfyLiveness.framework/IdenfyLiveness
  Expected in:     .../Frameworks/Lottie.framework/Lottie

Any ideas?

**Comment by fir1** [comment]
Hi @viktasidenfy,

Would you be able to help us please ? We are trying to integrate your SDK into our IOS app, and we can not resolved the above mentioned issues.

Thanks.

**Comment by viktasidenfy** [comment]
Hello,
Sorry for the inconvenience. Next time, please create a ticket at techsupport@idenfy.com.
Just double checking, as I understand, our sample application without any configuration changes crashes with the following error?
The problem seems to be with the lottie-ios framework. Could you please share the xCode version and iOS version of the simulator/device you are running on, so we could replicate this on our side.

**Comment by epodkorytov** [comment]
Hi @viktasidenfy, 

We are constantly using the latest versions of Xcode, iOS, cocoapods and other.  xcode 14.2/14.3 iOS 16.4  M1Max, but 'iDenfySDK/iDenfyLiveness', '7.8.0' started on i7  xcode 14.2.1 iOS 16.0.1

It looks like you're using an older version of the framework that conflicts with the newer version. I've faced this issue before where the framework in the project conflicted with a statically linked subordinate version.

**Comment by viktasidenfy** [comment]
Currently for me, the 7.8.1 version works fine on the i7 with xcode 14.2. I'll try on an M1 chip as well.
Also, I will deploy a stage version of the SDK with unconstrained version of lottie, so you could change the version in your podfile and test if any of the newer versions is working.

**Comment by viktasidenfy** [comment]
@epodkorytov I've published 1.1.2 version of our SDK. It will use the latest version of lottie. Please try it out ant let me know if the issue still persists.

**Comment by dbHLIS** [comment]
Hi @viktasidenfy / iDenfy team!,

Added IdenfySDK with Cocoapods. 
pod 'iDenfySDK/iDenfyLiveness', '7.8.1'
Processor : Intel i5
OS : macOS Monterey 12.6.2
Xcode Version : 14.1

dyld[5514]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <D4513EDD-1992-38A6-AC4B-5596B46DE6C9> /private/var/containers/Bundle/Application/EFCEB806-4CAB-463F-89F9-8F041A39B680/Kappagee.app/Frameworks/IdenfyLiveness.framework/IdenfyLiveness
  Expected in:     <EA296102-02EC-30F3-95BB-49A21066C0AE> /private/var/containers/Bundle/Application/EFCEB806-4CAB-463F-89F9-8F041A39B680/Kappagee.app/Frameworks/Lottie.framework/Lottie
Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <D4513EDD-1992-38A6-AC4B-5596B46DE6C9> /private/var/containers/Bundle/Application/EFCEB806-4CAB-463F-89F9-8F041A39B680/Kappagee.app/Frameworks/IdenfyLiveness.framework/IdenfyLiveness
  Expected in:     <EA296102-02EC-30F3-95BB-49A21066C0AE> /private/var/containers/Bundle/Application/EFCEB806-4CAB-463F-89F9-8F041A39B680/Kappagee.app/Frameworks/Lottie.framework/Lottie
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by viktasidenfy** [comment]
@epodkorytov Hello, please, try out version  pod 'iDenfySDK/iDenfyLiveness', '1.1.2' and let me know if the issue still persists

**Comment by dbHLIS** [comment]
Hi @viktasidenfy / iDenfy team!,

Added IdenfySDK with Cocoapods.
pod 'iDenfySDK/iDenfyLiveness', ‘8.2.2’
Processor : M1 pro / M1
OS : macOS Sonoma 14.0
Xcode Version : 15.0

dyld[3342]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
  Referenced from: <1F51A94D-292D-3BB1-8694-7ECA964B1833> /private/var/containers/Bundle/Application/DE4392C8-2BF3-4326-ADB2-BF7CEC7A0FC4/Kappagee.app/Frameworks/IdenfyLiveness.framework/IdenfyLiveness
  Expected in:     <A3ED4FD3-EF80-3157-9F5C-BC8FEBB8250A> /private/var/containers/Bundle/Application/DE4392C8-2BF3-4326-ADB2-BF7CEC7A0FC4/Kappagee.app/Frameworks/Lottie.framework/Lottie
