### ISSUE TITLE
Crash on Initial Run

### ISSUE THREAD

**Issue by dbHLIS** [idenfy/Documentation#98]
Hi @viktasidenfy / iDenfy team!,

Added IdenfySDK with Cocoapods.
pod 'iDenfySDK/iDenfyLiveness', ‘8.2.2’
Processor : M1 pro / M1
OS : macOS Sonoma 14.0
Xcode Version : 15.0

dyld[3342]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
Referenced from: <1F51A94D-292D-3BB1-8694-7ECA964B1833> /private/var/containers/Bundle/Application/DE4392C8-2BF3-4326-ADB2-BF7CEC7A0FC4/Kappagee.app/Frameworks/IdenfyLiveness.framework/IdenfyLiveness
Expected in: /private/var/containers/Bundle/Application/DE4392C8-2BF3-4326-ADB2-BF7CEC7A0FC4/Kappagee.app/Frameworks/Lottie.framework/Lottie

**Comment by viktasidenfy** [comment]
@dbHLIS make sure you have included the deployment target in the post_install script of the podfile, same as in our sample application:

`config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'`

**Comment by dbHLIS** [comment]
Hello @viktasidenfy 
Still getting same kind of error,

Logs ~

> dyld[9603]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
>   Referenced from: <1F51A94D-292D-3BB1-8694-7ECA964B1833> /private/var/containers/Bundle/Application/58361905-AF39-47BF-ABAA-163945F930D1/Kappagee.app/Frameworks/IdenfyLiveness.framework/IdenfyLiveness
>   Expected in:     <9DFBC901-B241-3ADC-B3CA-636C96BC664E> /private/var/containers/Bundle/Application/58361905-AF39-47BF-ABAA-163945F930D1/Kappagee.app/Frameworks/Lottie.framework/Lottie

  
post_install Script ~ 
```
installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
    
    installer.aggregate_targets.each do |target|
        target.xcconfigs.each do |variant, xcconfig|
            xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
            IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
                xcconfig_path = config.base_configuration_reference.real_path
                IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
            end
        end
    end
```

**Comment by viktasidenfy** [comment]
@dbHLIS have you updated cocoapods to 1.13? Please check our [sample application ](https://github.com/idenfy/Documentation/blob/master/resources/sdk/ios/tutorials/sample/idenfy_sample_ios.zip) and check if it has the same issue. If not, the post_install script is the issue here.
